version: '3.7'

services:
    mysql:
        container_name: adm_videos_mysql
        command: --innodb-use-native-aio=0
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: adm_videos
        security_opt:
            - seccomp:unconfined
        volumes:
            - .docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - adm_videos_network

    app:
        container_name: adm_videos_app
        profiles: ["app"]
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8081:8081"
        networks:
            - adm_videos_network
        depends_on:
            - mysql

networks:
    adm_videos_network:
        driver: bridge
